[{block name="details_relatedproducts_alsobought"}]
	[{if $oView->getAlsoBoughtTheseProducts()}]
		[{include file="widget/product/list.tpl" type="grid" listId="alsoBought" header="light" head="PAGE_DETAILS_CUSTOMERS_ALSO_BOUGHT"|oxmultilangassign products=$oView->getAlsoBoughtTheseProducts()}]
	[{/if}]
[{/block}]

[{block name="details_relatedproducts_crossselling"}]
    [{if $oView->getCrossSelling()|count}]
        [{capture append="oxidBlock_productbar"}]
            [{include file="widget/product/boxproducts.tpl" listId="cross" header="lightHead" head="WIDGET_PRODUCT_RELATED_PRODUCTS_CROSSSELING_HEADER"|oxmultilangassign products=$oView->getCrossSelling() }]
        [{/capture}]
    [{/if}]
[{/block}]

[{block name="details_relatedproducts_similarproducts"}]
    [{if $oView->getSimilarProducts()|count}]
        [{capture append="oxidBlock_productbar" }]
            [{include file="widget/product/boxproducts.tpl" listId="similar" header="lightHead" head="WIDGET_PRODUCT_RELATED_PRODUCTS_SIMILAR_HEADER"|oxmultilangassign products=$oView->getSimilarProducts() }]
        [{/capture}]
    [{/if }]
[{/block}]

[{block name="details_relatedproducts_accessoires"}]
    [{if $oView->getAccessoires()|count}]
        [{capture append="oxidBlock_productbar"}]
            [{include file="widget/product/boxproducts.tpl" listId="accessories" header="lightHead" head="WIDGET_PRODUCT_RELATED_PRODUCTS_ACCESSORIES_HEADER"|oxmultilangassign products=$oView->getAccessoires() }]
        [{/capture}]
    [{/if }]
[{/block}]

[{block name="details_relatedproducts_lastseen"}]
    [{if $oView->getLastProducts()}]
        [{capture append="oxidBlock_productbar"}]
            [{include file="widget/product/boxproducts.tpl" listId="lastSeen" header="lightHead" head="DETAILS_LASTSEENPRODUCTS"|oxmultilangassign products=$oView->getLastProducts() }]
        [{/capture}]
    [{/if }]
[{/block}]

[{if $oxidBlock_productbar}]
    <div id="relProducts" class="relatedProducts">
      [{foreach from=$oxidBlock_productbar item="_block"}]
        [{$_block}]
      [{/foreach}]
    </div>
[{/if }]