[{assign var="oDetailsProduct" value=$oView->getProduct()}]
[{assign var="currency" value=$oView->getActCurrency()}]
[{assign var="oPictureProduct" value=$oView->getPicturesProduct()}]

[{include file="page/details/inc/details.tpl"}]

[{*if $oViewConf->getFbAppId()}]
    [{gn2_oxscript add="$(function(){oxFacebook.initDetailsPagePartial();});"}]
[{/if}]
[{if $oView->showZoomPics()}]
    [{gn2_oxscript add="$( '#zoomTrigger' ).oxModalPopup({target:'#zoomModal'});"}]
    [{gn2_oxscript add="$( '#morePicsContainer' ).oxMorePictures();"}]
    [{gn2_oxscript add="$('.cloud-zoom, .cloud-zoom-gallery').CloudZoom();"}]
[{/if}]
[{gn2_oxscript add="$( '#productTitle' ).oxArticleActionLinksSelect();"}]
[{gn2_oxscript add="$( '#amountPrice' ).oxAmountPriceSelect();"}]
[{gn2_oxscript add="$( 'div.dropDown p' ).oxDropDown();"}]
[{gn2_oxscript add="$( 'div.tabbedWidgetBox' ).tabs();"}]
[{gn2_oxscript add="$( 'a.js-external' ).attr('target', '_blank');"}]
[{gn2_oxscript add="$( '#reviewRating' ).oxRating({openReviewForm: false, hideReviewButton: false});"}]
[{gn2_oxscript add="$( '#writeNewReview' ).oxReview();"}]
[{gn2_oxscript add="$( '#variants' ).oxArticleVariant();"}]

[{gn2_oxscript*}]