[{if $oxcmp_basket->isNewItemAdded() && $oView->getNewBasketItemMsgType() == 2}]
[{include file="widget/minibasket/minibasket.tpl" _prefix="modal"}]
[{gn2_oxscript add="$('#modalbasketFlyout').oxModalPopup({ target: '#modalbasketFlyout', openDialog: true, width: 'auto'});"}]
    [{gn2_oxscript add="if ($('.scrollable .scrollbarBox').length > 0) { $('.scrollable .scrollbarBox').jScrollPane({showArrows: true, verticalArrowPositions: 'split' });}"}]
    [{gn2_oxscript add="$('#modalbasketFlyout').css('z-index','inherit');"}]
[{/if}]